# Generated by Django 3.2.2 on 2021-05-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='component',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='parentId',
            field=models.IntegerField(null=True),
        ),
    ]
