# Generated by Django 3.2.2 on 2021-05-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210514_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.FilePathField()),
                ('parentId', models.IntegerField(null=True)),
                ('enabled', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('component', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
