# Generated by Django 3.2.2 on 2021-05-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_coursemessage_homeimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemessage',
            name='recommendedBookIntro',
            field=models.CharField(max_length=255),
        ),
    ]
