# Generated by Django 3.2.2 on 2021-05-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_coursemessage_recommendedbookintro'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemessage',
            name='introImg',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
