# Generated by Django 3.2.2 on 2021-05-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_teachingresources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingresources',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
