# Generated by Django 3.2.2 on 2021-05-19 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_referencebooks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name_plural': '菜单管理'},
        ),
    ]
