# Generated by Django 3.2.2 on 2021-05-19 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210519_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='pattern',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='menu',
            name='pattern',
            field=models.CharField(max_length=50),
        ),
    ]
